//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> Cleaning_wIPSI_U { get; set; }
        public Nullable<long> Cleaning_wIPSC_Uofs { get; set; }
        public Nullable<double> Cleaning_IPSC_rI1 { get; set; }
        public Nullable<double> Cleaning_IPSC_rI2 { get; set; }
        public Nullable<long> Cleaning_wIPSC_U1 { get; set; }
        public Nullable<long> Cleaning_wIPSC_U2 { get; set; }
        public Nullable<double> Cleaning_rGas_Ia { get; set; }
        public Nullable<long> Cleaning_wTime { get; set; }
        public Nullable<long> Cleaning_wTStblz_ { get; set; }
        public Nullable<long> Cleaning_xUseGV1 { get; set; }
        public Nullable<long> Cleaning_xUseGV2 { get; set; }
        public Nullable<long> Cleaning_xUseGV3 { get; set; }
        public Nullable<long> Cleaning_GMFC1_wSetControl { get; set; }
        public Nullable<double> Cleaning_GMFC1_rSetGasNominal { get; set; }
        public Nullable<double> Cleaning_GMFC1_rSetAmperage { get; set; }
        public Nullable<double> Cleaning_GMFC1_rSetPressure_ { get; set; }
        public Nullable<double> Cleaning_GMFC1_rSetRatio_ { get; set; }
        public Nullable<double> Cleaning_GMFC1_rSetIntergral_ { get; set; }
        public Nullable<double> Cleaning_GMFC1_rSetProportional { get; set; }
        public Nullable<long> Cleaning_GMFC2_wSetControl_ { get; set; }
        public Nullable<double> Cleaning_GMFC2_rSetGasNominal { get; set; }
        public Nullable<double> Cleaning_GMFC2_rSetAmperage__ { get; set; }
        public Nullable<double> Cleaning_GMFC2_rSetPressure { get; set; }
        public Nullable<double> Cleaning_GMFC2_rSetRatio_ { get; set; }
        public Nullable<double> Cleaning_GMFC2_rSetIntergral_ { get; set; }
        public Nullable<double> Cleaning_GMFC2_rSetProportional { get; set; }
        public Nullable<long> Cleaning_GMFC3_wSetControl_ { get; set; }
        public Nullable<double> Cleaning_GMFC3_rSetGasNominal { get; set; }
        public Nullable<double> Cleaning_GMFC3_rSetAmperage__ { get; set; }
        public Nullable<double> Cleaning_GMFC3_rSetPressure { get; set; }
        public Nullable<double> Cleaning_GMFC3_rSetRatio__ { get; set; }
        public Nullable<double> Cleaning_GMFC3_rSetIntergral { get; set; }
        public Nullable<double> Cleaning_GMFC3_rSetProportional { get; set; }
    }
}
