//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heating
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> Heating_wTemp { get; set; }
        public Nullable<long> Heating_wTime { get; set; }
        public Nullable<double> Heating_rMaxPressure { get; set; }
        public Nullable<double> Heating_rWorkPressure { get; set; }
        public Nullable<double> Heating_rMinPower { get; set; }
        public Nullable<double> Heating_rMaxPower { get; set; }
        public Nullable<double> Heating_rPID_Kp { get; set; }
        public Nullable<double> Heating_rPID_Ti { get; set; }
        public Nullable<double> Heating_rPID_Td { get; set; }
        public Nullable<long> Heating_xNotTurnOff { get; set; }
        public Nullable<long> Heating_wHeatingMode { get; set; }
        public Nullable<long> Heating_wPower { get; set; }
        public Nullable<long> Heating_wRampTm1 { get; set; }
    }
}
